version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    step:
      - checkout
      - run:
        name: Install AWS Command Line Interface
        working_directory: /
        command: |
          sudo apt-get update
          sudo apt-get install -y
          python-pip python-dev
          sudo pip install awscli
          aws --version
