version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python-pip python-dev
      - run: sudo pip install awscli
      - run: aws --version
