version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y python-pip python-dev
      - run: sudo pip install awscli
      - run: aws --version
      - run: aws deploy push --profile tawkdeployer --application-name tawkify-app --s3-location s3://tawkify-cd-revisions/tawkify_branch_$CIRCLE_BRANCH.zip --ignore-hidden-files --source ~/working_directory/tawkify-app
